### ISSUE TITLE
Hibernate 6.2 compatibility

### ISSUE THREAD

**Issue by mkomko** [Blazebit/blaze-persistence#1685]
### Description
Hibernate 6.2 moved some classes around, so the Hibernate60MetadataContributor is no longer compatible.

### Expected behavior
Blaze Persistence works with Hibernate 6.2.

### Actual behavior
java.lang.NoClassDefFoundError: org/hibernate/cfg/InheritanceState
	at com.blazebit.persistence.integration.hibernate.Hibernate60MetadataContributor.addEntity(Hibernate60MetadataContributor.java:62)
	at com.blazebit.persistence.integration.hibernate.Hibernate60MetadataContributor.contribute(Hibernate60MetadataContributor.java:53)

### Environment
Version:            1.6.8
JPA-Provider:    Hibernate 6.2.0.CR2
Application Server: WildFly 27

**Comment by beikov** [comment]
Thanks for reporting. I'll make sure that we get something working again for the next release.

**Comment by EugenMayer** [comment]
This issue becomes a little more gravity due to https://discourse.hibernate.org/t/hibernate-error-when-upgrading-from-6-1-0-final-to-6-1-1-final-or-later/6798
